version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'develop'
    schedule:
      interval: 'weekly'
    groups:
      minor-and-patch:
        update-types:
          - 'minor'
          - 'patch'
    open-pull-requests-limit: 10

  - package-ecosystem: 'npm'
    directory: '/cli'
    target-branch: 'develop'
    schedule:
      interval: 'weekly'
    groups:
      minor-and-patch:
        update-types:
          - 'minor'
          - 'patch'
    open-pull-requests-limit: 10

  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'develop'
    schedule:
      interval: 'weekly'
