services:
  - type: web
    name: js-challenge
    env: node
    buildCommand: npm ci --include=dev && node ace build && vite build && node ace migration:run --force && node ace db:seed
    startCommand: node build/bin/server.js
    healthCheckPath: /health
    envVars:
      - key: TZ
        value: UTC
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: LOG_LEVEL
        value: info
      - key: APP_KEY
        sync: false
      - key: DOMAIN
        value: https://js-challenge.onrender.com
      - key: NODE_ENV
        value: production
      - key: SESSION_DRIVER
        value: cookie
      # Database configuration
      - key: DATABASE_URL
        sync: false # À configurer dans l'interface Render avec l'URL Neon complète
      # GitHub OAuth
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: OAUTH_GITHUB_CALLBACK_URL
        value: https://js-challenge.onrender.com/oauth/github/callback
      # Redis configuration
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      # SMTP configuration
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
databases:
  - name: js_challengedb
    databaseName: js_challengedb
    user: js_challengedb_owner
    ipAllowList: [] # autorise toutes les connexions
