services:
  - type: web
    name: codojo
    runtime: node
    buildCommand: npm ci --include=dev && npm run build && npx vite build
    preDeployCommand: node ace migration:run --force
    initialDeployHook: node ace db:seed
    startCommand: node build/bin/server.js
    healthCheckPath: /health
    envVars:
      - key: TZ
        value: UTC
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: LOG_LEVEL
        value: info
      - key: APP_KEY
        sync: false
      - key: DOMAIN
        value: https://codojo.ekodevs.com
      - key: PUBLIC_APP_URL
        value: https://codojo.ekodevs.com
      - key: NODE_ENV
        value: production
      - key: SESSION_DRIVER
        value: cookie
      # Database configuration
      - key: DB_HOST
        fromDatabase:
          name: codojo-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: codojo-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: codojo-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: codojo-db
          property: password
      - key: DB_DATABASE
        fromDatabase:
          name: codojo-db
          property: database
      # GitHub OAuth
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: OAUTH_GITHUB_CALLBACK_URL
        value: https://codojo.ekodevs.com/oauth/github/callback
      # Redis configuration
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      # SMTP configuration
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
databases:
  - name: codojo-db
    databaseName: codojo
    user: codojo_owner
    ipAllowList: [] # autorise toutes les connexions
    plan: free
