services:
  - type: web
    name: js-challenge
    env: node
    buildCommand: npm ci && node ace build && node ace migration:run --force && node ace db:seed
    startCommand: node build/bin/server.js
    healthCheckPath: /health
    envVars:
      - key: TZ
        value: UTC
      - key: HOST
        value: 0.0.0.0
      - key: LOG_LEVEL
        value: info
      - key: APP_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: SESSION_DRIVER
        value: cookie
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false

databases:
  - name: js-challengedb
    database: js-challengedb
    user: js-challengedb_owner
    password: vYpO4Qr3fdIK
    host: ep-shy-math-a4p6o7xf-pooler.us-east-1.aws.neon.tech
    port: 5432
    ssl: true
