/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['id', 'tokenableId', 'type', 'name', 'hash', 'abilities', 'createdAt', 'updatedAt', 'lastUsedAt', 'expiresAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column()
  declare name: string | null
  @column()
  declare hash: string
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
}

export class ExerciseSchema extends BaseModel {
  static $columns = ['id', 'number', 'title', 'description', 'difficulty', 'createdAt', 'updatedAt'] as const
  $columns = ExerciseSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare number: number
  @column()
  declare title: string
  @column()
  declare description: string
  @column()
  declare difficulty: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserProgressSchema extends BaseModel {
  static $columns = ['id', 'exerciseId', 'userId', 'completed', 'isUnlocked', 'completedAt', 'unlockedAt'] as const
  $columns = UserProgressSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare exerciseId: number
  @column()
  declare userId: string
  @column()
  declare completed: boolean | null
  @column()
  declare isUnlocked: boolean | null
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime()
  declare unlockedAt: DateTime | null
}

export class UserSolutionSchema extends BaseModel {
  static $columns = ['id', 'exerciseId', 'userId', 'code', 'createdAt', 'updatedAt'] as const
  $columns = UserSolutionSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare exerciseId: number
  @column()
  declare userId: string
  @column()
  declare code: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'username', 'email', 'password', 'totalPoints', 'avatar', 'oauthProviderId', 'oauthProviderName', 'createdAt', 'updatedAt', 'emailVerifiedAt'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare username: string
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare totalPoints: number
  @column()
  declare avatar: string | null
  @column()
  declare oauthProviderId: string | null
  @column()
  declare oauthProviderName: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
}
