/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AdminActivityLogSchema extends BaseModel {
  static $columns = ['id', 'actorId', 'action', 'entityType', 'entityId', 'reason', 'metadata', 'createdAt'] as const
  $columns = AdminActivityLogSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare actorId: string
  @column()
  declare action: string
  @column()
  declare entityType: string
  @column()
  declare entityId: string
  @column()
  declare reason: string | null
  @column()
  declare metadata: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['id', 'tokenableId', 'type', 'name', 'hash', 'abilities', 'createdAt', 'updatedAt', 'lastUsedAt', 'expiresAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column()
  declare name: string | null
  @column()
  declare hash: string
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
}

export class ExerciseSchema extends BaseModel {
  static $columns = ['id', 'number', 'title', 'description', 'difficulty', 'createdAt', 'updatedAt', 'slug', 'category', 'points', 'status', 'starterCode', 'hint', 'prerequisiteId'] as const
  $columns = ExerciseSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare number: number
  @column()
  declare title: string
  @column()
  declare description: string
  @column()
  declare difficulty: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare slug: string | null
  @column()
  declare category: string
  @column()
  declare points: number
  @column()
  declare status: string
  @column()
  declare starterCode: string | null
  @column()
  declare hint: string | null
  @column()
  declare prerequisiteId: number | null
}

export class SubmissionSchema extends BaseModel {
  static $columns = ['id', 'userId', 'exerciseId', 'status', 'client', 'clientVersion', 'language', 'idempotencyKey', 'code', 'accepted', 'results', 'errorMessage', 'startedAt', 'completedAt', 'createdAt', 'updatedAt'] as const
  $columns = SubmissionSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: string
  @column()
  declare exerciseId: number
  @column()
  declare status: string
  @column()
  declare client: string
  @column()
  declare clientVersion: string | null
  @column()
  declare language: string
  @column()
  declare idempotencyKey: string | null
  @column()
  declare code: string
  @column()
  declare accepted: boolean | null
  @column()
  declare results: any | null
  @column()
  declare errorMessage: string | null
  @column.dateTime()
  declare startedAt: DateTime | null
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TokenAuthAccessTokenSchema extends BaseModel {
  static $columns = ['id', 'createdAt', 'updatedAt'] as const
  $columns = TokenAuthAccessTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserProgressSchema extends BaseModel {
  static $columns = ['id', 'exerciseId', 'userId', 'completed', 'isUnlocked', 'completedAt', 'unlockedAt'] as const
  $columns = UserProgressSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare exerciseId: number
  @column()
  declare userId: string
  @column()
  declare completed: boolean | null
  @column()
  declare isUnlocked: boolean | null
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime()
  declare unlockedAt: DateTime | null
}

export class UserSolutionSchema extends BaseModel {
  static $columns = ['id', 'exerciseId', 'userId', 'code', 'createdAt', 'updatedAt'] as const
  $columns = UserSolutionSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare exerciseId: number
  @column()
  declare userId: string
  @column()
  declare code: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'username', 'email', 'password', 'totalPoints', 'avatar', 'oauthProviderId', 'oauthProviderName', 'createdAt', 'updatedAt', 'emailVerifiedAt', 'role', 'status', 'suspendedAt', 'suspendedBy', 'suspensionReason'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare username: string
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare totalPoints: number
  @column()
  declare avatar: string | null
  @column()
  declare oauthProviderId: string | null
  @column()
  declare oauthProviderName: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare role: string
  @column()
  declare status: string
  @column.dateTime()
  declare suspendedAt: DateTime | null
  @column()
  declare suspendedBy: string | null
  @column()
  declare suspensionReason: string | null
}
